apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web-namespace  # Especifica el namespace
spec:
  selector:
    app: web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30000
  type: NodePort