apiVersion: v1
kind: ConfigMap
metadata:
  name: exporter-config
  namespace: web-namespace
data:
  config.hcl: |
    listen {
      port = 9113
    }

    namespace "nginx" {
      source = {
        files = ["/var/log/nginx/access.log"]
      }

      format = "$remote_addr - $remote_user [$time_local] \"$request\" $status $body_bytes_sent \"$http_referer\" \"$http_user_agent\" \"$http_x_forwarded_for\" $request_time"

      labels {
        app = "default"
      }

      histogram_buckets = [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1]
    }