apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: web-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
      annotations:
        # Stub exporter (9114)
        prometheus.io/scrape:       "true"
        prometheus.io/port:         "9114"
        # Log exporter (9113)
        prometheus.io/scrape-logs:  "true"
        prometheus.io/logs-port:    "9113"
    spec:
      containers:
        - name: nginx
          image: openresty/openresty:alpine
          resources:
            requests:
              cpu:    "100m"    # reserva 0.01 CPU
              memory: "32Mi"   # reserva 32Mi de RAM
            limits:
              cpu:    "100m"    # máximo 0.02 CPU
              memory: "32Mi"   # máximo 64Mi de RAM
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
            - name: nginx-logs
              mountPath: /var/log/nginx
            - name: loaderio-volume
              mountPath: /usr/share/nginx/html/loaderio-f10362eea9532a3072056c547d3d7196.txt
              subPath: loaderio-f10362eea9532a3072056c547d3d7196.txt

        - name: prometheus-nginxlog-exporter
          image: ghcr.io/martin-helmich/prometheus-nginxlog-exporter/exporter:v1
          args:
            - "-config-file"
            - "/etc/prometheus-nginxlog-exporter/config.hcl"
          ports:
            - containerPort: 9113
          volumeMounts:
            - name: exporter-config
              mountPath: /etc/prometheus-nginxlog-exporter/config.hcl
              subPath: config.hcl
            - name: nginx-logs
              mountPath: /var/log/nginx

        - name: nginx-stub-exporter
          image: nginx/nginx-prometheus-exporter:latest
          args:
            - "-web.listen-address=:9114"
            - "-nginx.scrape-uri=http://127.0.0.1/nginx_status"
          ports:
            - name: stub-metrics
              containerPort: 9114

      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: exporter-config
          configMap:
            name: exporter-config
        - name: nginx-logs
          emptyDir: {}
        - name: loaderio-volume
          configMap:
            name: loaderio-config