apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-k8s-sd
rules:
  - apiGroups: [""]
    resources:
      - pods
      - services
      - endpoints
      - nodes
    verbs: ["list", "watch"]
  - apiGroups: ["extensions", "apps"]
    resources:
      - deployments
      - replicasets
    verbs: ["list", "watch"]