apiVersion: v1
kind: Service
metadata:
  name: rstudio-service
  namespace: rstudio-namespace
spec:
  type: NodePort
  selector:
    app: rstudio
  ports:
  - protocol: TCP
    port: 8787
    targetPort: 8787
    nodePort: 30087   # Asegúrate de que este puerto esté libre en tus nodos